name: Deploy function code to AWS Lambda

on:
  push:
    branches:
      - main
      - fix/dashboard

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
        AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Zip the code
      run: |
        zip function.zip function.py
      working-directory: ./function
      
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Update Function Code
      run: |
        aws lambda update-function-code \
          --function-name llmetricsLambda \
          --zip-file fileb://function.zip
      working-directory: ./function
