name: Deploy function code to AWS Lambda

on:
  push:
    branches:
      - fix/cleanup-trace-mode
    paths:
      - 'function/**'  # Changes in function
      - '.github/workflows/**'  # Changes in pipelines

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Zip the code
      run: |
        zip -r function.zip .
      working-directory: ./function
      
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Update Function Code
      run: |
        aws lambda update-function-code \
          --function-name llmetricsLambda \
          --zip-file fileb://function.zip
      working-directory: ./function
    
    - name: Get AWS Account ID
      run: |
        AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
        echo "AWS_ACCOUNT_ID=$AWS_ACCOUNT_ID" >> $GITHUB_ENV

    - name: Add Required Permissions for Function Role
      run: |
        aws iam put-role-policy \
          --role-name llmetricsDynamoLambda \
          --policy-name DynamoDB-Index-Access \
          --policy-document '{
              "Version": "2012-10-17",
              "Statement": [
                  {
                      "Effect": "Allow",
                      "Action": [
                          "dynamodb:Query",
                          "dynamodb:Scan"
                      ],
                      "Resource": [
                          "arn:aws:dynamodb:${{ secrets.AWS_REGION }}:${{ env.ACCOUNT_ID }}:table/BenchmarkMetrics/index/*"
                      ]
                  }
              ]
          }'
    
    - name: Verify added policy
      run: |
        aws iam get-role-policy \
          --role-name llmetricsDynamoLambda \
          --policy-name DynamoDB-Index-Access
